// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod kinnector_config {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum MetadataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Metadata<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Metadata<'a> {
  type Inner = Metadata<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> Metadata<'a> {
  pub const VT_PLATFORM: flatbuffers::VOffsetT = 4;
  pub const VT_BASELINE_VERSION: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Metadata { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args MetadataArgs<'args>
  ) -> flatbuffers::WIPOffset<Metadata<'bldr>> {
    let mut builder = MetadataBuilder::new(_fbb);
    if let Some(x) = args.baseline_version { builder.add_baseline_version(x); }
    if let Some(x) = args.platform { builder.add_platform(x); }
    builder.finish()
  }


  #[inline]
  pub fn platform(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Metadata::VT_PLATFORM, None)
  }
  #[inline]
  pub fn baseline_version(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Metadata::VT_BASELINE_VERSION, None)
  }
}

impl flatbuffers::Verifiable for Metadata<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("platform", Self::VT_PLATFORM, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("baseline_version", Self::VT_BASELINE_VERSION, false)?
     .finish();
    Ok(())
  }
}
pub struct MetadataArgs<'a> {
    pub platform: Option<flatbuffers::WIPOffset<&'a str>>,
    pub baseline_version: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for MetadataArgs<'a> {
  #[inline]
  fn default() -> Self {
    MetadataArgs {
      platform: None,
      baseline_version: None,
    }
  }
}

pub struct MetadataBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> MetadataBuilder<'a, 'b> {
  #[inline]
  pub fn add_platform(&mut self, platform: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Metadata::VT_PLATFORM, platform);
  }
  #[inline]
  pub fn add_baseline_version(&mut self, baseline_version: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Metadata::VT_BASELINE_VERSION, baseline_version);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MetadataBuilder<'a, 'b> {
    let start = _fbb.start_table();
    MetadataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Metadata<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Metadata<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Metadata");
      ds.field("platform", &self.platform());
      ds.field("baseline_version", &self.baseline_version());
      ds.finish()
  }
}
pub enum PathExclusionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PathExclusion<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PathExclusion<'a> {
  type Inner = PathExclusion<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> PathExclusion<'a> {
  pub const VT_PATH_PREFIX: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PathExclusion { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args PathExclusionArgs<'args>
  ) -> flatbuffers::WIPOffset<PathExclusion<'bldr>> {
    let mut builder = PathExclusionBuilder::new(_fbb);
    if let Some(x) = args.path_prefix { builder.add_path_prefix(x); }
    builder.finish()
  }


  #[inline]
  pub fn path_prefix(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(PathExclusion::VT_PATH_PREFIX, None)
  }
}

impl flatbuffers::Verifiable for PathExclusion<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("path_prefix", Self::VT_PATH_PREFIX, false)?
     .finish();
    Ok(())
  }
}
pub struct PathExclusionArgs<'a> {
    pub path_prefix: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for PathExclusionArgs<'a> {
  #[inline]
  fn default() -> Self {
    PathExclusionArgs {
      path_prefix: None,
    }
  }
}

pub struct PathExclusionBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> PathExclusionBuilder<'a, 'b> {
  #[inline]
  pub fn add_path_prefix(&mut self, path_prefix: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PathExclusion::VT_PATH_PREFIX, path_prefix);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> PathExclusionBuilder<'a, 'b> {
    let start = _fbb.start_table();
    PathExclusionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PathExclusion<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PathExclusion<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PathExclusion");
      ds.field("path_prefix", &self.path_prefix());
      ds.finish()
  }
}
pub enum TrustedSignerOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TrustedSigner<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TrustedSigner<'a> {
  type Inner = TrustedSigner<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> TrustedSigner<'a> {
  pub const VT_SIGNER_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_TEAM_ID: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TrustedSigner { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TrustedSignerArgs<'args>
  ) -> flatbuffers::WIPOffset<TrustedSigner<'bldr>> {
    let mut builder = TrustedSignerBuilder::new(_fbb);
    if let Some(x) = args.team_id { builder.add_team_id(x); }
    if let Some(x) = args.signer_name { builder.add_signer_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn signer_name(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TrustedSigner::VT_SIGNER_NAME, None)
  }
  #[inline]
  pub fn team_id(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TrustedSigner::VT_TEAM_ID, None)
  }
}

impl flatbuffers::Verifiable for TrustedSigner<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("signer_name", Self::VT_SIGNER_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("team_id", Self::VT_TEAM_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct TrustedSignerArgs<'a> {
    pub signer_name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub team_id: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for TrustedSignerArgs<'a> {
  #[inline]
  fn default() -> Self {
    TrustedSignerArgs {
      signer_name: None,
      team_id: None,
    }
  }
}

pub struct TrustedSignerBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TrustedSignerBuilder<'a, 'b> {
  #[inline]
  pub fn add_signer_name(&mut self, signer_name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TrustedSigner::VT_SIGNER_NAME, signer_name);
  }
  #[inline]
  pub fn add_team_id(&mut self, team_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TrustedSigner::VT_TEAM_ID, team_id);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TrustedSignerBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TrustedSignerBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TrustedSigner<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TrustedSigner<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TrustedSigner");
      ds.field("signer_name", &self.signer_name());
      ds.field("team_id", &self.team_id());
      ds.finish()
  }
}
pub enum TrustedCLIOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TrustedCLI<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TrustedCLI<'a> {
  type Inner = TrustedCLI<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> TrustedCLI<'a> {
  pub const VT_BINARY_PATH: flatbuffers::VOffsetT = 4;
  pub const VT_CATEGORY_FLAGS: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TrustedCLI { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TrustedCLIArgs<'args>
  ) -> flatbuffers::WIPOffset<TrustedCLI<'bldr>> {
    let mut builder = TrustedCLIBuilder::new(_fbb);
    builder.add_category_flags(args.category_flags);
    if let Some(x) = args.binary_path { builder.add_binary_path(x); }
    builder.finish()
  }


  #[inline]
  pub fn binary_path(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TrustedCLI::VT_BINARY_PATH, None)
  }
  #[inline]
  pub fn category_flags(&self) -> u32 {
    self._tab.get::<u32>(TrustedCLI::VT_CATEGORY_FLAGS, Some(0)).unwrap()
  }
}

impl flatbuffers::Verifiable for TrustedCLI<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("binary_path", Self::VT_BINARY_PATH, false)?
     .visit_field::<u32>("category_flags", Self::VT_CATEGORY_FLAGS, false)?
     .finish();
    Ok(())
  }
}
pub struct TrustedCLIArgs<'a> {
    pub binary_path: Option<flatbuffers::WIPOffset<&'a str>>,
    pub category_flags: u32,
}
impl<'a> Default for TrustedCLIArgs<'a> {
  #[inline]
  fn default() -> Self {
    TrustedCLIArgs {
      binary_path: None,
      category_flags: 0,
    }
  }
}

pub struct TrustedCLIBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TrustedCLIBuilder<'a, 'b> {
  #[inline]
  pub fn add_binary_path(&mut self, binary_path: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TrustedCLI::VT_BINARY_PATH, binary_path);
  }
  #[inline]
  pub fn add_category_flags(&mut self, category_flags: u32) {
    self.fbb_.push_slot::<u32>(TrustedCLI::VT_CATEGORY_FLAGS, category_flags, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TrustedCLIBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TrustedCLIBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TrustedCLI<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TrustedCLI<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TrustedCLI");
      ds.field("binary_path", &self.binary_path());
      ds.field("category_flags", &self.category_flags());
      ds.finish()
  }
}
pub enum NetworkCDNOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NetworkCDN<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for NetworkCDN<'a> {
  type Inner = NetworkCDN<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> NetworkCDN<'a> {
  pub const VT_DOMAIN_SUFFIX: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    NetworkCDN { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args NetworkCDNArgs<'args>
  ) -> flatbuffers::WIPOffset<NetworkCDN<'bldr>> {
    let mut builder = NetworkCDNBuilder::new(_fbb);
    if let Some(x) = args.domain_suffix { builder.add_domain_suffix(x); }
    builder.finish()
  }


  #[inline]
  pub fn domain_suffix(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(NetworkCDN::VT_DOMAIN_SUFFIX, None)
  }
}

impl flatbuffers::Verifiable for NetworkCDN<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("domain_suffix", Self::VT_DOMAIN_SUFFIX, false)?
     .finish();
    Ok(())
  }
}
pub struct NetworkCDNArgs<'a> {
    pub domain_suffix: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for NetworkCDNArgs<'a> {
  #[inline]
  fn default() -> Self {
    NetworkCDNArgs {
      domain_suffix: None,
    }
  }
}

pub struct NetworkCDNBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> NetworkCDNBuilder<'a, 'b> {
  #[inline]
  pub fn add_domain_suffix(&mut self, domain_suffix: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NetworkCDN::VT_DOMAIN_SUFFIX, domain_suffix);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> NetworkCDNBuilder<'a, 'b> {
    let start = _fbb.start_table();
    NetworkCDNBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<NetworkCDN<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for NetworkCDN<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("NetworkCDN");
      ds.field("domain_suffix", &self.domain_suffix());
      ds.finish()
  }
}
pub enum SensitiveFileOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SensitiveFile<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SensitiveFile<'a> {
  type Inner = SensitiveFile<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> SensitiveFile<'a> {
  pub const VT_FILE_PATH: flatbuffers::VOffsetT = 4;
  pub const VT_CATEGORY_FLAGS: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SensitiveFile { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args SensitiveFileArgs<'args>
  ) -> flatbuffers::WIPOffset<SensitiveFile<'bldr>> {
    let mut builder = SensitiveFileBuilder::new(_fbb);
    builder.add_category_flags(args.category_flags);
    if let Some(x) = args.file_path { builder.add_file_path(x); }
    builder.finish()
  }


  #[inline]
  pub fn file_path(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SensitiveFile::VT_FILE_PATH, None)
  }
  #[inline]
  pub fn category_flags(&self) -> u32 {
    self._tab.get::<u32>(SensitiveFile::VT_CATEGORY_FLAGS, Some(0)).unwrap()
  }
}

impl flatbuffers::Verifiable for SensitiveFile<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("file_path", Self::VT_FILE_PATH, false)?
     .visit_field::<u32>("category_flags", Self::VT_CATEGORY_FLAGS, false)?
     .finish();
    Ok(())
  }
}
pub struct SensitiveFileArgs<'a> {
    pub file_path: Option<flatbuffers::WIPOffset<&'a str>>,
    pub category_flags: u32,
}
impl<'a> Default for SensitiveFileArgs<'a> {
  #[inline]
  fn default() -> Self {
    SensitiveFileArgs {
      file_path: None,
      category_flags: 0,
    }
  }
}

pub struct SensitiveFileBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> SensitiveFileBuilder<'a, 'b> {
  #[inline]
  pub fn add_file_path(&mut self, file_path: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SensitiveFile::VT_FILE_PATH, file_path);
  }
  #[inline]
  pub fn add_category_flags(&mut self, category_flags: u32) {
    self.fbb_.push_slot::<u32>(SensitiveFile::VT_CATEGORY_FLAGS, category_flags, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> SensitiveFileBuilder<'a, 'b> {
    let start = _fbb.start_table();
    SensitiveFileBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SensitiveFile<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SensitiveFile<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SensitiveFile");
      ds.field("file_path", &self.file_path());
      ds.field("category_flags", &self.category_flags());
      ds.finish()
  }
}
pub enum RulesDatabaseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RulesDatabase<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RulesDatabase<'a> {
  type Inner = RulesDatabase<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> RulesDatabase<'a> {
  pub const VT_VERSION: flatbuffers::VOffsetT = 4;
  pub const VT_EPOCH_TIMESTAMP: flatbuffers::VOffsetT = 6;
  pub const VT_METADATA: flatbuffers::VOffsetT = 8;
  pub const VT_EXCLUSIONS: flatbuffers::VOffsetT = 10;
  pub const VT_TRUSTED_SIGNERS: flatbuffers::VOffsetT = 12;
  pub const VT_TRUSTED_CLIS: flatbuffers::VOffsetT = 14;
  pub const VT_NETWORK_CDNS: flatbuffers::VOffsetT = 16;
  pub const VT_SENSITIVE_FILES: flatbuffers::VOffsetT = 18;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RulesDatabase { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RulesDatabaseArgs<'args>
  ) -> flatbuffers::WIPOffset<RulesDatabase<'bldr>> {
    let mut builder = RulesDatabaseBuilder::new(_fbb);
    builder.add_epoch_timestamp(args.epoch_timestamp);
    if let Some(x) = args.sensitive_files { builder.add_sensitive_files(x); }
    if let Some(x) = args.network_cdns { builder.add_network_cdns(x); }
    if let Some(x) = args.trusted_clis { builder.add_trusted_clis(x); }
    if let Some(x) = args.trusted_signers { builder.add_trusted_signers(x); }
    if let Some(x) = args.exclusions { builder.add_exclusions(x); }
    if let Some(x) = args.metadata { builder.add_metadata(x); }
    builder.add_version(args.version);
    builder.finish()
  }


  #[inline]
  pub fn version(&self) -> u32 {
    self._tab.get::<u32>(RulesDatabase::VT_VERSION, Some(0)).unwrap()
  }
  #[inline]
  pub fn epoch_timestamp(&self) -> u64 {
    self._tab.get::<u64>(RulesDatabase::VT_EPOCH_TIMESTAMP, Some(0)).unwrap()
  }
  #[inline]
  pub fn metadata(&self) -> Option<Metadata<'a>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<Metadata>>(RulesDatabase::VT_METADATA, None)
  }
  #[inline]
  pub fn exclusions(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<PathExclusion<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<PathExclusion>>>>(RulesDatabase::VT_EXCLUSIONS, None)
  }
  #[inline]
  pub fn trusted_signers(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TrustedSigner<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TrustedSigner>>>>(RulesDatabase::VT_TRUSTED_SIGNERS, None)
  }
  #[inline]
  pub fn trusted_clis(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TrustedCLI<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TrustedCLI>>>>(RulesDatabase::VT_TRUSTED_CLIS, None)
  }
  #[inline]
  pub fn network_cdns(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<NetworkCDN<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<NetworkCDN>>>>(RulesDatabase::VT_NETWORK_CDNS, None)
  }
  #[inline]
  pub fn sensitive_files(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SensitiveFile<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SensitiveFile>>>>(RulesDatabase::VT_SENSITIVE_FILES, None)
  }
}

impl flatbuffers::Verifiable for RulesDatabase<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("version", Self::VT_VERSION, false)?
     .visit_field::<u64>("epoch_timestamp", Self::VT_EPOCH_TIMESTAMP, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<Metadata>>("metadata", Self::VT_METADATA, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<PathExclusion>>>>("exclusions", Self::VT_EXCLUSIONS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<TrustedSigner>>>>("trusted_signers", Self::VT_TRUSTED_SIGNERS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<TrustedCLI>>>>("trusted_clis", Self::VT_TRUSTED_CLIS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<NetworkCDN>>>>("network_cdns", Self::VT_NETWORK_CDNS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<SensitiveFile>>>>("sensitive_files", Self::VT_SENSITIVE_FILES, false)?
     .finish();
    Ok(())
  }
}
pub struct RulesDatabaseArgs<'a> {
    pub version: u32,
    pub epoch_timestamp: u64,
    pub metadata: Option<flatbuffers::WIPOffset<Metadata<'a>>>,
    pub exclusions: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<PathExclusion<'a>>>>>,
    pub trusted_signers: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TrustedSigner<'a>>>>>,
    pub trusted_clis: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TrustedCLI<'a>>>>>,
    pub network_cdns: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<NetworkCDN<'a>>>>>,
    pub sensitive_files: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SensitiveFile<'a>>>>>,
}
impl<'a> Default for RulesDatabaseArgs<'a> {
  #[inline]
  fn default() -> Self {
    RulesDatabaseArgs {
      version: 0,
      epoch_timestamp: 0,
      metadata: None,
      exclusions: None,
      trusted_signers: None,
      trusted_clis: None,
      network_cdns: None,
      sensitive_files: None,
    }
  }
}

pub struct RulesDatabaseBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RulesDatabaseBuilder<'a, 'b> {
  #[inline]
  pub fn add_version(&mut self, version: u32) {
    self.fbb_.push_slot::<u32>(RulesDatabase::VT_VERSION, version, 0);
  }
  #[inline]
  pub fn add_epoch_timestamp(&mut self, epoch_timestamp: u64) {
    self.fbb_.push_slot::<u64>(RulesDatabase::VT_EPOCH_TIMESTAMP, epoch_timestamp, 0);
  }
  #[inline]
  pub fn add_metadata(&mut self, metadata: flatbuffers::WIPOffset<Metadata<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Metadata>>(RulesDatabase::VT_METADATA, metadata);
  }
  #[inline]
  pub fn add_exclusions(&mut self, exclusions: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<PathExclusion<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RulesDatabase::VT_EXCLUSIONS, exclusions);
  }
  #[inline]
  pub fn add_trusted_signers(&mut self, trusted_signers: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<TrustedSigner<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RulesDatabase::VT_TRUSTED_SIGNERS, trusted_signers);
  }
  #[inline]
  pub fn add_trusted_clis(&mut self, trusted_clis: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<TrustedCLI<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RulesDatabase::VT_TRUSTED_CLIS, trusted_clis);
  }
  #[inline]
  pub fn add_network_cdns(&mut self, network_cdns: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<NetworkCDN<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RulesDatabase::VT_NETWORK_CDNS, network_cdns);
  }
  #[inline]
  pub fn add_sensitive_files(&mut self, sensitive_files: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<SensitiveFile<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RulesDatabase::VT_SENSITIVE_FILES, sensitive_files);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RulesDatabaseBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RulesDatabaseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RulesDatabase<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RulesDatabase<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RulesDatabase");
      ds.field("version", &self.version());
      ds.field("epoch_timestamp", &self.epoch_timestamp());
      ds.field("metadata", &self.metadata());
      ds.field("exclusions", &self.exclusions());
      ds.field("trusted_signers", &self.trusted_signers());
      ds.field("trusted_clis", &self.trusted_clis());
      ds.field("network_cdns", &self.network_cdns());
      ds.field("sensitive_files", &self.sensitive_files());
      ds.finish()
  }
}
#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_root_as_rules_database<'a>(buf: &'a [u8]) -> RulesDatabase<'a> {
  unsafe { flatbuffers::root_unchecked::<RulesDatabase<'a>>(buf) }
}

#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_size_prefixed_root_as_rules_database<'a>(buf: &'a [u8]) -> RulesDatabase<'a> {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<RulesDatabase<'a>>(buf) }
}

#[inline]
/// Verifies that a buffer of bytes contains a `RulesDatabase`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rules_database_unchecked`.
pub fn root_as_rules_database(buf: &[u8]) -> Result<RulesDatabase, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<RulesDatabase>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `RulesDatabase` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_rules_database_unchecked`.
pub fn size_prefixed_root_as_rules_database(buf: &[u8]) -> Result<RulesDatabase, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<RulesDatabase>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `RulesDatabase` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rules_database_unchecked`.
pub fn root_as_rules_database_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RulesDatabase<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<RulesDatabase<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `RulesDatabase` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rules_database_unchecked`.
pub fn size_prefixed_root_as_rules_database_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RulesDatabase<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<RulesDatabase<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a RulesDatabase and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `RulesDatabase`.
pub unsafe fn root_as_rules_database_unchecked(buf: &[u8]) -> RulesDatabase {
  flatbuffers::root_unchecked::<RulesDatabase>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed RulesDatabase and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `RulesDatabase`.
pub unsafe fn size_prefixed_root_as_rules_database_unchecked(buf: &[u8]) -> RulesDatabase {
  flatbuffers::size_prefixed_root_unchecked::<RulesDatabase>(buf)
}
#[inline]
pub fn finish_rules_database_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<RulesDatabase<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_rules_database_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<RulesDatabase<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod KinnectorConfig

